### ISSUE TITLE
Audio bitrate lower

### ISSUE THREAD

**Issue by ghost** [petrkotek/chromecastize#14]
After the conversion the audio bitrate is lower than before. For example, with a movie I had first 640Kbps and than 276Kbps. It's not a big problem, but I'll search for a solution.

**Comment by pfrenssen** [comment]
It is very difficult to closely match the input bitrate. The most realistic option would be to use a constant bitrate, but in most cases this would give worse results than using the variable bitrates we are using now.

There is now the possibility to pass custom options to the encoder by specifying them in the `config.sh` file, so you can now set your preferred bitrate there.
