### ISSUE TITLE
*.ok Invalid argument

### ISSUE THREAD

**Issue by ghost** [petrkotek/chromecastize#20]
This is the error:

Processing: Movies/About Time.mkv
- general: Matroska -> ok
- video: AVC -> copy
- audio: AC-3 -> libvorbis
- video length: 02:03:22.144
  [NULL @ 0x7f0a4e64a7e0] Unable to find a suitable output format for 'Movies/About Time.mkv.ok'
  Movies/About Time.mkv.ok: Invalid argument
- failed to convert 'Movies/About Time.mkv' (or conversion has been interrupted)
- deleting partially converted file...

**Comment by manatlan** [comment]
Same trouble here ...

But found an easy patch .... just rename "ok" -> "ok.mkv" in source file (lines : 131 & 156)
And all goes right

**Comment by MattScherbatsky** [comment]
Now it works! Thank you!

**Comment by pfrenssen** [comment]
Fixed by #28.
