### ISSUE TITLE
Multi thread options

### ISSUE THREAD

**Issue by alaintxu** [petrkotek/chromecastize#21]
I'm not sure if your app is using multithread. Avconv/ffmpeg have **-threads auto** option or even specifying the amount of threads to use **-threads 2**. You can add these options to the app in order to get shorter codification times.

**Comment by cstich** [comment]
The script is using multithreading (at least in my case)

**Comment by pfrenssen** [comment]
The `-threads auto` option is the default. It depends though on the codecs that are being used. If you see that not all your threads are being used this probably means that the codec doesn't support more threads.
