### ISSUE TITLE
ffmpeg install not recognized

### ISSUE THREAD

**Issue by sethlo** [petrkotek/chromecastize#23]
I installed ffmpeg on linux 14.04 server using this guide: https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu

ffmpeg appears to be running fine.  
When I enter command "which fmpeg" I receive response: /home/myusername/bin/ffmpeg
When I run chromecastize, I receive an error that ffmpeg is not installed as follows:
`avconv` (or `ffmpeg`) is not available, please install it

Forgive me, as I am noob.  Don't know if this is the right way to report this, or ask for help.  Perhaps my install of ffmpeg needs to be moved somewhere else?

**Comment by pfrenssen** [comment]
You have ffmpeg installed in your user space. Are you also running chromecastize with the same user?

**Comment by pfrenssen** [comment]
Closing for lack of response.
