### ISSUE TITLE
Is the avconv check necessary?

### ISSUE THREAD

**Issue by DrCherry** [petrkotek/chromecastize#26]
I'm running arch and since there's no avconv utility, I simply removed it from the check and everything seems to be working as it should.  Is the check for avconv necessary for other distros?  If not, I'd like to propose it be removed, I can issue a pull request...

**Comment by murzz** [comment]
Some distros have livab instead of ffmpeg, that’s why the check was added.

**Comment by petrkotek** [comment]
correct - `libav` (i.e. `avconv`) and `ffmpeg` are more or less compatible, so either of them can be used.

@DrCherry you mentioned, that it works fine without the check, but i believe it works fine even with the check, is that correct?

**Comment by pfrenssen** [comment]
I have committed a fix in #34 that suppresses the error message on systems such as Arch that do not have avconv installed.
