### ISSUE TITLE
Filenames with spaces

### ISSUE THREAD

**Issue by cbowman57** [petrkotek/chromecastize#37]
It appears that with the latest commit filenames with spaces are no longer processed.

**Comment by pfrenssen** [comment]
Thanks for the report! I've just seen that quotes are missing around the filename, that's probably causing it. It seems this was working by accident before, and the fix for #35 has exposed this bug.

Will post a fix shortly.

**Comment by cbowman57** [comment]
I figured it was something as simple as that.  But I'm no script wizard.  ;-)

One addition I do make, for my own convenience, is moving the $1.bak to trash with gvfs-trash.

Thanks for getting on it so quickly.

**Comment by pfrenssen** [comment]
There was an older feature request to automatically remove the *.bak files: #4. That has not been implemented yet though but it seems like a worthwhile addition.

**Comment by cbowman57** [comment]
I find it convenient.

Initially I deleted them but opted to send them to trash, just in case.
