### ISSUE TITLE
Support deletion of `.bak`files

### ISSUE THREAD

**Issue by petrkotek** [petrkotek/chromecastize#4]
Currently original file gets renamed to `.bak`. Would be nice to support removal of original files, e.g. by renaming them to unique extension such as `.ccbak` and then removing by `find` command

**Comment by toxic0berliner** [comment]
a nice alternative exists in my fork : https://github.com/toxic0berliner/chromecastize
- it does not create a .bak file (original file is kept as is, transcoded file has .mp4 extension)
- you can turn --autodelete on and it will automatically delete all transcoded files
- if you do not turn autodelete on, it will generate a script that you can run later, the script launches mplayer for you to check video quality and audio sync, and after playback it asks you if you want to delete the original file, if not it asks if you want to delete the transcoded file, and if not it will not delete anything.

Alson the ffmpeg options have been reworked : I'm doing 2 pass for video ensuring the best quality possible for transcode...

**Comment by pfrenssen** [comment]
Fixed in #58
