### ISSUE TITLE
Still level 5.2

### ISSUE THREAD

**Issue by carlogarro** [petrkotek/chromecastize#59]
Hello, after using this in one of my video files, it is suposed to be ready for chromecast but Plex still says that my server is not powerfull enough. It says that I should be level 4.2 and that I am level 5.1.

Process followed:

> Processing: ../../Downloads/Series/The Sopranos/Season 3/The Sopranos - S03E01 - Mr. Ruggerio's Neighborhood HDTV-720p.mkv
> - general: Matroska -> ok
> - input video profile: High@L5.1
> - video: AVC -> copy
> - audio: AC-3 -> libvorbis
> - video length: 00:47:11.800
> [matroska,webm @ 0xb3f4f0] Read error at pos. 1668452740 (0x63729184)3941.7kbits/s                                                                                                frame=70795 fps=1252 q=-1.0 Lsize= 1363994kB time=00:47:11.68 bitrate=3946.0kbits/s
> conversion succeeded; file '../../Downloads/Series/The Sopranos/Season 3/The Sopranos - S03E01 - Mr. Ruggerio's Neighborhood HDTV-720p.mkv' saved
> renaming original file as '../../Downloads/Series/The Sopranos/Season 3/The Sopranos - S03E01 - Mr. Ruggerio's Neighborhood HDTV-720p.mkv.bak'

When I chech with mediainfo my file after chromecastize it still says: `Format profile : High@L5.1 `

Do you guys have some idea? Thank you.

> [Chromecast] [MDE] Augmented profile: { "directPlay": { "mp4": { "mimeType": "video/mp4; codecs=\"avc1.42E01E\"", "video": { "codecs": { "h264": { "maxLevel": 42 } }, "maxWidth": 1920, "maxHeight": 1080, "maxBitDepth": 8, "maxFrameRate": 60 }, "audio": { "codecs": { "aac": { "maxSamplingRate": 48000, "maxChannels": 2 }, "mp3": {}, "ac3": {} } } }, "mkv": { "mimeType": "video/webm", "video": { "codecs": { "h264": { "maxLevel": 42 }, "vp8": {} }, "maxWidth": 1920, "maxHeight": 1080, "maxBitDepth": 8, "maxFrameRate": 60 }, "audio": { "codecs": { "aac": { "maxSamplingRate": 48000, "maxChannels": 2 }, "mp3": {}, "vorbis": {}, "ac3": {} } } }, "mpegts": { "protocol": "hls", "video": { "maxWidth": 1920, "maxHeight": 1080, "maxBitDepth": 8, "maxFrameRate": 60 }, "audio": { "codecs": { "ac3": {} } } } }, "directStream": { "video": { "maxWidth": 1920, "maxHeight": 1080, "maxBitDepth": 8, "maxFrameRate": 60, "codecs": { "h264": { "maxLevel": 42 } } }, "audio": { "codecs": { "aac": { "maxSamplingRate": 48000, "maxChannels": 2 }, "mp3": {}, "opus": {}, "vorbis": {} }, "maxChannels": 6 } } }

**Comment by bartlaarhoven** [comment]
AVC is a supported video codec. Chromecastize finds the video to be AVC and therefore doesn't change anything about the original video format. That includes the format profile.

What you could do is remove `AVC` from your `SUPPORTED_VCODEC` in your `config.sh` file. That way, you'll force chromecastize to convert your video. That will then happen to almost all of your videos though, be warned. You better use that separately on the files or folder that you encounter issues with and leave the `SUPPORTED_VCODEC` to a sane default for the rest.

**Comment by pfrenssen** [comment]
You can uncomment the `FORCE_VENCODE=1` option in the configuration, this will always force a re-encoding of the file to a supported bitrate. Be warned though that it will also re-encode files that are already in a supported profile. Chromecastize does not yet have an option to only encode when the video profile exceeds the supported profiles.

See this section in the configuration options:
```
# Option to force re-encoding of the video stream. Uncomment this if you want to
# ensure that the video will always be using your encoding options and the
# resulting bitrate will be supported by your device.
#FORCE_VENCODE=1
```
